/**
 * Spectra — AI Investigation Summary Panel
 * Calls Claude via the backend to generate an intelligence analyst summary
 * for a synthetic person.
 */
import { useState } from 'react'
import { getPersonSummary } from '../../api/persons'

interface AISummaryPanelProps {
    personId: string
}

export default function AISummaryPanel({ personId }: AISummaryPanelProps) {
    const [summary, setSummary] = useState<string | null>(null)
    const [loading, setLoading] = useState(false)
    const [error, setError] = useState<string | null>(null)

    const handleGenerate = async () => {
        setLoading(true)
        setError(null)
        try {
            const data = await getPersonSummary(personId)
            setSummary(data.summary)
        } catch (e: unknown) {
            setError((e as { message?: string }).message ?? 'Failed to generate summary')
        } finally {
            setLoading(false)
        }
    }

    return (
        <div className="rounded-xl border border-slate-700 bg-slate-900/60 p-5">
            <div className="flex items-center justify-between mb-4">
                <h3 className="text-slate-200 font-semibold flex items-center gap-2">
                    <span className="text-violet-400">🤖</span>
                    AI Intelligence Report
                </h3>
                <button
                    id="ai-summary-btn"
                    onClick={handleGenerate}
                    disabled={loading}
                    className="px-4 py-2 rounded-lg bg-violet-600 hover:bg-violet-500 disabled:opacity-50
                        text-white text-sm font-medium transition-all flex items-center gap-2"
                >
                    {loading ? (
                        <>
                            <span className="animate-spin text-xs">⟳</span>
                            Claude is analyzing…
                        </>
                    ) : (
                        <>✨ Generate Intelligence Report</>
                    )}
                </button>
            </div>

            {error && (
                <div className="text-red-400 text-sm bg-red-500/10 border border-red-500/30 rounded-lg p-3">
                    {error}
                </div>
            )}

            {summary && (
                <div className="mt-2">
                    {/* Document-style container */}
                    <div className="relative bg-slate-950/80 border border-violet-500/20 rounded-lg p-5
                        shadow-inner shadow-violet-950/30">
                        {/* Document header */}
                        <div className="flex items-center justify-between mb-4 pb-3 border-b border-slate-700">
                            <div className="flex items-center gap-2">
                                <span className="text-violet-500 text-xs font-mono font-bold tracking-widest uppercase">
                                    CLASSIFIED — SYNTHETIC DATA
                                </span>
                            </div>
                            <span className="text-slate-500 text-xs font-mono">
                                SPECTRA/INTEL/{new Date().toISOString().split('T')[0]}
                            </span>
                        </div>
                        {/* Report body */}
                        <div className="text-slate-300 text-sm leading-relaxed space-y-4 font-serif">
                            {summary.split('\n\n').map((para, i) => (
                                <p key={i}>{para}</p>
                            ))}
                        </div>
                        {/* Document footer */}
                        <div className="mt-4 pt-3 border-t border-slate-700 flex items-center justify-between">
                            <span className="text-slate-600 text-xs font-mono">
                                Generated by Claude Sonnet · All data is 100% synthetic
                            </span>
                            <span className="text-slate-600 text-xs">⚠️ No real persons represented</span>
                        </div>
                    </div>
                </div>
            )}

            {!summary && !loading && !error && (
                <div className="text-slate-600 text-sm text-center py-8 border border-dashed border-slate-700 rounded-lg">
                    Click "Generate Intelligence Report" to have Claude analyze this synthetic profile
                </div>
            )}
        </div>
    )
}
