/**
 * Spectra — About / Ethics Page
 */
import Layout from '../components/layout/Layout'

const PRINCIPLES = [
    {
        icon: '🧪',
        title: 'Synthetic Data Only',
        body: 'Every person, event, and location in Spectra is generated by algorithms. No real individual has ever been added to this system.',
    },
    {
        icon: '🔒',
        title: 'No Surveillance',
        body: 'Spectra does not connect to any camera, phone, or network. It cannot track, see, or monitor any real human being.',
    },
    {
        icon: '📚',
        title: 'Educational Purpose',
        body: 'This project exists solely to demonstrate data engineering, graph analytics, and anomaly detection techniques for learning.',
    },
    {
        icon: '⚖️',
        title: 'Why Real Surveillance Is Dangerous',
        body: 'Mass surveillance erodes privacy, chills free expression, enables discrimination, and gives disproportionate power to institutions. Building real surveillance systems without rigorous oversight causes measurable harm.',
    },
    {
        icon: '🌐',
        title: 'Open Source & Auditable',
        body: 'All code is open and auditable. There are no hidden data streams or secret endpoints. What you see is exactly what runs.',
    },
]

export default function AboutPage() {
    return (
        <Layout>
            <div className="max-w-3xl mx-auto">
                <div className="text-center mb-12">
                    <div className="text-5xl mb-4">🛡️</div>
                    <h1 className="text-3xl font-black text-slate-100">Ethics & About Spectra</h1>
                    <p className="text-slate-500 mt-3 max-w-xl mx-auto">
                        Spectra is an educational simulation. Every design decision prioritises transparency and ethical responsibility.
                    </p>
                </div>

                {/* Big warning block */}
                <div className="rounded-2xl border border-amber-500/30 bg-amber-500/10 p-6 mb-10">
                    <div className="flex items-start gap-4">
                        <span className="text-3xl mt-1">⚠️</span>
                        <div>
                            <h2 className="text-amber-300 font-bold text-lg mb-2">Ethics Notice</h2>
                            <p className="text-amber-200/80 text-sm leading-relaxed">
                                Spectra uses <strong>100% computer-generated, synthetic data</strong>. No real person's name, location, event,
                                or communication is stored or processed. The data generation engine uses Faker + NumPy libraries to produce
                                statistically plausible but entirely fictional datasets. This system cannot and does not surveil real people.
                            </p>
                        </div>
                    </div>
                </div>

                {/* Principles */}
                <div className="space-y-4">
                    {PRINCIPLES.map((p) => (
                        <div key={p.title} className="rounded-xl border border-slate-800 bg-slate-900/40 p-5 flex gap-4">
                            <span className="text-2xl mt-0.5">{p.icon}</span>
                            <div>
                                <h3 className="text-slate-200 font-semibold mb-1">{p.title}</h3>
                                <p className="text-slate-500 text-sm leading-relaxed">{p.body}</p>
                            </div>
                        </div>
                    ))}
                </div>

                {/* Tech stack */}
                <div className="mt-12 rounded-xl border border-slate-800 bg-slate-900/40 p-6">
                    <h2 className="text-slate-300 font-semibold mb-4">Tech Stack</h2>
                    <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                        {[
                            ['FastAPI', 'Backend API'],
                            ['PostgreSQL', 'Relational DB'],
                            ['Neo4j', 'Graph DB'],
                            ['Redis', 'Cache'],
                            ['React + Vite', 'Frontend'],
                            ['IsolationForest', 'Anomaly ML'],
                        ].map(([name, role]) => (
                            <div key={name} className="rounded-lg bg-slate-800/60 p-3">
                                <p className="text-slate-200 text-sm font-medium">{name}</p>
                                <p className="text-slate-600 text-xs">{role}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </Layout>
    )
}
